package com.zaziapps.mtg_scanner.data.repository

import android.util.Log
import com.google.firebase.auth.FirebaseAuth
import com.zaziapps.mtg_scanner.data.model.MagicCard
import com.zaziapps.mtg_scanner.network.ScryfallApiService
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import retrofit2.Response
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

/**
 * Repository component handling external network communications with the Scryfall API endpoint.
 * Configures secure transmission interceptors containing identity headers and manages remote card metadata queries.
 */
class ScryfallRepository {

    /**
     * Remote API service instance generated by Retrofit to execute HTTP networking routines.
     */
    private val apiService: ScryfallApiService

    init {
        // Configure the HTTP network client injection layers including custom user-agent identification headers.
        val okHttpClient = OkHttpClient.Builder()
            .addInterceptor { chain ->
                // Resolve authenticated user profile properties safely from the active Firebase session environment.
                val currentUser = FirebaseAuth.getInstance().currentUser
                val userEmail = currentUser?.email ?: "anonymous@magicscanapp.com"

                // Structure standardized user-agent identifier signatures to conform to external API developer compliance guidelines.
                val userAgentValue = "MagicScanApp/1.0 ($userEmail)"

                val request = chain.request().newBuilder()
                    .header("User-Agent", userAgentValue)
                    .header("Accept", "application/json")
                    .build()
                chain.proceed(request)
            }
            .build()

        // Build the Retrofit abstraction client infrastructure mapped to handle asynchronous server message serialization.
        val retrofit = Retrofit.Builder()
            .baseUrl("https://api.scryfall.com/")
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()

        apiService = retrofit.create(ScryfallApiService::class.java)
    }

    /**
     * Search a card by name in the specified language.
     *
     * @param cardName Name of the card.
     * @param language Language of the input text (cardName) - Default = "en".
     * @return MagicCard if a result is found | null if nothing is found or an error occurs.
     */
    suspend fun searchByNameAndLanguage(cardName: String, language: String = "en"): MagicCard? {
        // Shift thread context distribution allocation models off the graphical thread into the standard input-output pipeline pool.
        return withContext(Dispatchers.IO) {
            try {
                // Formulate target network syntax constraints requiring strict matching rules on titles and language properties.
                val query = "lang:$language !\"$cardName\""
                val response = apiService.searchCard(query)

                // Verify communication transmission statuses to trap failed queries or uninitialized payload returns.
                if (!response.isSuccessful || response.body() == null) {
                    logError(response)
                    return@withContext null
                }

                val cardsArray = response.body()!!.data
                // Enforce safety boundary checks against blank list allocations to eliminate initialization mismatches.
                if (cardsArray.isEmpty()) return@withContext null

                // Extract the baseline record representing the exact matched product profile.
                return@withContext cardsArray[0]

            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }

    /**
     * Search by oracle id in the specified language.
     *
     * @param oracleId Oracle BD identifier.
     * @param language Language of the desired card - Default = "en".
     * @return MagicCard if a result is found | null if nothing is found or an error occurs.
     */
    suspend fun searchByOracleIdAndLanguage(oracleId: String?, language: String = "en"): MagicCard? {
        // Redirect execution threads down into resource optimization blocks to handle data fetching routines asynchronously.
        return withContext(Dispatchers.IO) {
            try {
                // Construct specialized query strings targeting unique engine components paired with target localizers.
                val query = "oracle_id:$oracleId lang:$language"
                val response = apiService.searchCard(query)

                // Verify request completeness statuses before unwrapping data collection properties.
                if (response.isSuccessful && response.body() != null) {
                    val cardsArray = response.body()!!.data
                    if (cardsArray.isEmpty()) return@withContext null
                    return@withContext cardsArray[0]
                } else {
                    // Record telemetry errors to handle unavailable local translations while logging server diagnostics.
                    Log.w("Scryfall", "Found card : $language")
                    logError(response)
                    null
                }

            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }

    /**
     * Retrieves all cards belonging to the same set expansion in the specified language.
     *
     * @param setCode The unique 3 or 4 letter expansion/set identifier code (e.g., "neo").
     * @param language The language code filter for the returned cards - Default = "en".
     * @return A list of matching magic cards found, or an empty list if an error occurs.
     */
    suspend fun getCardsFromSetAndLanguage(setCode: String, language: String = "en"): List<MagicCard> {
        // Delegate operation handling structures over to IO dispatcher threads to maintain application fluidity.
        return withContext(Dispatchers.IO) {
            try {
                // Initialize clean, explicit query criteria parameters grouping catalog properties together.
                val query = "set:$setCode lang:$language"
                val response = apiService.searchCard(query)

                // Trap network transmission execution faults early to return predictable empty fallback collection structures.
                if (!response.isSuccessful || response.body() == null) {
                    logError(response)
                    return@withContext emptyList()
                }

                val cardsResponse = response.body()!!

                // Forward structural lists directly back down to consumer processing channels.
                return@withContext cardsResponse.data

            } catch (e: Exception) {
                e.printStackTrace()
                emptyList()
            }
        }
    }

    /**
     * Records telemetry network error details inside the diagnostic logger.
     *
     * @param response The unparsed raw HTTP networking response object containing status exceptions.
     */
    private fun logError(response: Response<*>) {
        val errorJson = response.errorBody()?.string()
        Log.e("ScryfallError", "Code HTTP: ${response.code()}")
        Log.e("ScryfallError", "Error details: $errorJson")
    }
}
