package com.zaziapps.mtg_scanner.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import com.zaziapps.mtg_scanner.data.local.scanned.MagicCardConverter
import com.zaziapps.mtg_scanner.data.local.scanned.ScannedCard
import com.zaziapps.mtg_scanner.data.local.scanned.ScannedCardDao
import com.zaziapps.mtg_scanner.data.local.lang.CardTranslations
import com.zaziapps.mtg_scanner.data.local.lang.CardLangDao

/**
 * Defines the central Room database configuration and architecture for the application.
 * Serves as the primary programmatic access point to the local persisted storage layers.
 */
@Database(
    entities = [
        ScannedCard::class,
        CardTranslations::class
    ],
    version = 2,
    exportSchema = false
)
@TypeConverters(MagicCardConverter::class)
abstract class AppDatabase : RoomDatabase() {

    /**
     * Provides access to the Data Access Object (DAO) managing user collection history logs.
     *
     * @return The concrete [ScannedCardDao] implementation generated by Room at runtime.
     */
    abstract fun scannedCardDao(): ScannedCardDao

    /**
     * Provides access to the Data Access Object (DAO) managing static card translation lookups.
     *
     * @return The concrete [CardLangDao] implementation generated by Room at runtime.
     */
    abstract fun cardLangDao(): CardLangDao

    companion object {

        /** Volatile reference used to ensure atomic updates to the shared database singleton instance across threads. */
        @Volatile
        private var INSTANCE: AppDatabase? = null

        /**
         * Resolves or instantiates the database singleton instance using thread-safe synchronization.
         * Clones precomputed lookup datasets directly out of the assets storage directory upon initialization.
         *
         * @param context The execution context used to resolve the global application space references.
         * @return The active [AppDatabase] instance ready to handle operational lifecycle queries.
         */
        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                                context.applicationContext,
                                AppDatabase::class.java,
                                "mtg_scanner.db"
                            )
                    .createFromAsset("databases/mtg_languages.db")
                    .fallbackToDestructiveMigration(false)
                    .build()
                INSTANCE = instance
                instance
            }
        }
    }
}
