package com.zaziapps.mtg_scanner.data.local.scanned

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.zaziapps.mtg_scanner.data.model.MagicCard

/**
 * Represents the database table structure mapped to store the history of cards scanned by the user.
 * This entity serves as the persistent record for tracking local collections and transaction logs.
 *
 * @property id The autogenerated primary key unique integer identifier for the local database entry record.
 * @property scryfallId The external unique tracking identifier linked to the target card profile entry on Scryfall.
 * @property name The standard structural reference name identifying the scanned card item.
 * @property urlImage The remote storage path address or image address pointer pointing to the card artwork layout source.
 * @property scanDate The precise system epoch timestamp calculation representing when the scan event happened.
 * @property magicCard The embedded complex domain object structure holding complete detailed mechanics of the specific card.
 */
@Entity(tableName = "scanned_cards")
data class ScannedCard(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val scryfallId: String,
    val name: String,
    val urlImage: String,
    val scanDate: Long = System.currentTimeMillis(),
    val magicCard: MagicCard
)
