package com.zaziapps.mtg_scanner.data.model

import android.graphics.Bitmap
import android.graphics.RectF
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.zaziapps.mtg_scanner.data.local.lang.CardTranslations

/**
 * Immutable state container enclosing the collection of currently active card tracks.
 * Engineered for efficient state allocation and smart recomposition within Jetpack Compose UI layout layers.
 *
 * @property cards The complete collection of active [CardDetection] targets currently tracked within the viewport frame.
 */
@Immutable
data class ScannerState(
    val cards: List<CardDetection> = emptyList()
)


// TODO: OnItemClick
/**
 * Data architecture component tracking an individual card object isolated by the vision system.
 * Encapsulates computer vision tracking metrics along with runtime UI reactive translations.
 *
 * @property id The temporary unique integer identifier assigned to distinguish this object track across consecutive execution frames.
 * @property boundingBox Relative spatial coordinates specifying the position mapping of the card boundary box on screen.
 * @property confidence Precision score indicating the classification accuracy certainty index generated by the machine learning model.
 * @property classId The target category classification index mapping to specific card layout frames.
 * @property bitmap The isolated high-resolution sub-bitmap slice showing only the target object canvas area.
 * @property framesAlive Count of consecutive frames where the object instance has maintained structural tracking alignment.
 */
data class CardDetection(
    val id: Int,
    val boundingBox: RectF,
    val confidence: Float,
    val classId: Int,
    val bitmap: Bitmap? = null,
    var framesAlive: Int = 1
) {
    /**
     * Observable reactive placeholder linking the tracked object layout instance directly to its localized database translation metadata.
     */
    var foundTranslation by mutableStateOf<CardTranslations?>(null)
}
